import React, { createContext, useContext } from 'react';
import { useLocalStorage } from '../hooks/useLocalStorage';

type Language = 'en' | 'tr' | 'it' | 'ar';

const translations = {
  en: {
    // General
    language_code: 'en-US',

    // Auth
    welcomeBack: 'Welcome Back!',
    createAccount: 'Create Account',
    signInToDashboard: 'Sign in to access your dashboard.',
    getStartedByCreatingAccount: 'Get started by creating a new account.',
    emailAddress: 'Email Address',
    password: 'Password',
    processing: 'Processing...',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    signInWithGoogle: 'Sign in with Google',
    dontHaveAccount: "Don't have an account? ",
    alreadyHaveAccount: "Already have an account? ",
    signUp: 'Sign Up',
    errorFirebaseConfigEmail: 'Configuration error. Please enable Email/Password sign-in provider in your Firebase project.',
    errorFirebaseConfigGoogle: 'Configuration error. Please enable the Google sign-in provider in your Firebase project.',
    errorGoogleSignIn: 'Failed to sign in with Google.',
    errorOccurred: 'An error occurred.',
    
    // Language Toggle
    changeLanguage: 'Change language, current is {{currentLanguage}}',
    language_en: 'English',
    language_tr: 'Türkçe',
    language_it: 'Italiano',
    language_ar: 'العربية',

    // Dashboard
    financialDashboard: 'Financial Dashboard',
    welcomeMessage: 'Welcome, <span class="font-semibold text-slate-300">{{email}}</span>',
    signOut: 'Sign Out',
    startNewMonthlyBudget: 'Start New Monthly Budget',
    welcomeToHub: 'Welcome to Your Financial Hub!',
    noBudgetsYet: "You haven't set up any monthly budgets yet. <br/>Click the button above to get started.",
    viewYearSummary: 'View {{year}} Summary',
    budget: 'Budget',
    viewDetailsFor: 'View details for {{month}}',
    deleteBudgetFor: 'Delete budget for {{month}}',
    
    // Monthly Setup
    newMonthlyBudget: 'New Monthly Budget',
    setBudgetForNewMonth: 'Set your budget for a new month.',
    year: 'Year',
    month: 'Month',
    monthlyBudgetLimit: 'Monthly Budget Limit',
    baseMonthlyIncome: 'Base Monthly Income',
    monthlyIncomeGoalOptional: 'Monthly Income Goal (Optional)',
    monthlyIncomeGoal: 'Monthly Income Goal',
    currency: 'Currency',
    cancel: 'Cancel',
    creating: 'Creating...',
    createBudget: 'Create Budget',
    errorMonthExists: 'A budget for {{monthId}} already exists.',
    errorInvalidLimit: 'Please enter a valid, positive number for the budget limit.',
    errorInvalidIncome: 'Please enter a valid, non-negative number for income.',
    errorInvalidIncomeGoal: 'Please enter a valid, non-negative number for the income goal.',
    eg1000: 'e.g., 1000',
    eg3000: 'e.g., 3000',
    eg4000: 'e.g., 4000',

    // Limit Setter (Initial Setup)
    welcome: 'Welcome!',
    setMonthlyBudgetPrompt: 'Set your monthly budget to get started.',
    monthlyIncome: 'Monthly Income',
    settingUp: 'Setting Up...',
    startTracking: 'Start Tracking',

    // Monthly View
    dashboard: 'Dashboard',
    export: 'Export',
    expenses: 'Expenses',
    trend: 'Trend',
    categories: 'Categories',
    income: 'Income',
    incomeTrend: 'Income Trend',
    recurring: 'Recurring',
    aiAdvisor: 'AI Advisor',

    // Summary
    totalSpent: 'Total Spent',
    remainingBudget: 'Remaining Budget',
    limit: 'Limit',
    completedIncome: 'Completed Income',
    editGoal: 'Edit Goal',
    setGoal: 'Set Goal',
    setIncomeGoal: 'Set income goal',
    saveIncomeGoal: 'Save income goal',
    cancelEditIncomeGoal: 'Cancel editing income goal',
    goal: 'Goal',
    noGoalSet: 'No goal set.',
    pendingIncome: 'Pending Income',
    potentialTotalIncome: 'Potential total income',
    categorySpending: 'Category Spending',
    editBudgets: 'Edit Budgets',
    setBudgets: 'Set Budgets',
    setCategoryBudgetsAndColors: 'Set Category Budgets & Colors',
    setColorFor: 'Set color for {{categoryName}}',
    colorPickerFor: 'Color picker for {{categoryName}}',
    overAllocatedBy: 'Over-allocated by:',
    remainingToAllocate: 'Remaining to Allocate:',
    allocated: 'Allocated',
    saving: 'Saving...',
    saveBudgets: 'Save Budgets',
    noCategoryBudgetsSet: "No category budgets set. Click 'Set Budgets' to allocate your spending limit.",
    aiFinancialSummary: 'AI Financial Summary',
    analyzing: 'Analyzing...',
    getAnalysis: 'Get Analysis',

    // Add Expense Form
    addNewExpense: 'Add New Expense',
    amount: 'Amount',
    description: 'Description',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    category: 'Category',
    addExpense: 'Add Expense',
    adding: 'Adding...',
    egCoffeeWithFriends: 'e.g., Coffee with friends',
    errorInvalidAmount: 'Please enter a valid, positive amount.',
    errorEmptyDescription: 'Description cannot be empty.',
    errorSelectCategory: 'Please select a category.',
    payInInstallments: 'Pay in installments',
    numberOfInstallments: 'Number of Installments',
    errorInvalidInstallments: 'Please enter a valid number of installments (minimum 2).',
    scanReceipt: 'Scan Receipt',
    uploadReceipt: 'Upload a receipt',

    // Expense List
    recentExpenses: 'Recent Expenses',
    searchExpenses: 'Search Expenses',
    searchByDescription: 'Search by description...',
    noExpensesAdded: 'No expenses added yet.',
    noExpensesMatchSearch: 'No expenses match your search.',
    paidBy: 'Paid by {{method}}',
    deleteExpenseFor: 'Delete expense for {{description}}',
    installmentLabel: 'Installment {{current}}/{{total}}',
    confirmPayment: 'Confirm Payment',
    paid: 'Paid',

    // Category View
    spendingByCategory: 'Spending by Category',
    percentageOfTotal: '{{percentage}}% of total',
    categoryTotals: 'Category Totals (Click to toggle)',
    grandTotal: 'Grand Total',
    noDataToDisplay: 'No data to display.',

    // Income View
    displayingIn: 'Displaying in <strong>{{code}}</strong>. Rate: 1 {{baseCode}} = {{rate}} {{code}}',
    addNewIncomeSource: 'Add New Income Source',
    sourceName: 'Source Name',
    egLessonWithAlex: 'e.g., Lesson with Alex',
    incomeSourceName: 'Income Source Name',
    incomeSourceAmount: 'Income Source Amount',
    addSource: 'Add Source',
    yourIncomeSources: 'Your Income Sources',
    quickAddPrompt: 'Quickly add a pending transaction or manage your sources.',
    transactionDate: 'Transaction Date',
    noIncomeSources: 'No income sources defined yet.',
    editSourceName: 'Edit Source Name',
    editSourceCategory: 'Edit Source Category',
    editSourceAmount: 'Edit Source Amount',
    save: 'Save',
    fromAmount: 'from {{symbol}}{{amount}}',
    addIncomeFrom: 'Add income from {{name}}',
    editSource: 'Edit source {{name}}',
    deleteSource: 'Delete source {{name}}',
    recentIncomeTransactions: 'Recent Income Transactions',
    noIncomeRecorded: 'No income recorded yet.',
    pending: 'Pending',
    markAsPaid: 'Mark transaction from {{name}} as paid',
    deleteTransactionFor: 'Delete transaction for {{name}}',
    completed: 'Completed',
    errorEnterSourceName: 'Please enter a source name.',
    errorInvalidDate: 'Please select a valid date for the transaction.',
    confirmDeleteSource: 'Are you sure you want to delete the income source "{{name}}"? This action cannot be undone.',

    // Recurring View
    manageRecurring: 'Manage Recurring Transactions',
    addRecurring: 'Add Recurring Transaction',
    transactionType: 'Transaction Type',
    startDate: 'Start Date',
    add: 'Add',
    noRecurringTransactions: 'No recurring transactions have been set up yet.',
    confirmDeleteRecurring: 'Are you sure you want to delete this recurring transaction? It will no longer be automatically added in the future.',
    nextOn: 'Next on: {{date}}',
    recurringExpenses: 'Recurring Expenses',
    recurringIncomes: 'Recurring Incomes',

    // AI Advisor View
    aiFinancialAdvisor: 'AI Financial Advisor',
    aiAdvisorDescription: 'Ask for personalized advice on how to manage your finances and save money based on your spending.',
    aiAdvisorPlaceholder: 'e.g., How can I reduce my food spending?',
    getAdvice: 'Get Advice',
    errorAiAdvice: 'Sorry, I was unable to generate advice at this time.',
    errorAiAnalysis: 'Sorry, I couldn\'t generate an analysis right now. Please try again later.',


    // Trend Views
    cumulativeSpendingTrend: 'Cumulative Spending Trend',
    cumulativeIncomeTrend: 'Cumulative Income Trend',
    day: 'Day',
    cumulative: 'Cumulative',
    noExpenseDataForTrend: 'No expense data to display trend.',
    noCompletedIncomeForTrend: 'No completed income data to display trend.',

    // Comparison View
    thisMonthVsLastMonth: 'This Month vs. Last Month',
    cumulativeSpendingComparison: 'Cumulative Spending Comparison',
    dayOfMonth: 'Day of Month',

    // Annual View
    annualSummary: '{{year}} Annual Summary',
    viewYear: 'View Year',
    previousYear: 'Previous year',
    nextYear: 'Next year',
    selectYearToView: 'Select year to view annual summary',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netBalance: 'Net Balance',
    net: 'Net',
    monthlyFinancialOverview: 'Monthly Financial Overview',
    underBudgetBy: 'Under Budget by',
    overBudgetBy: 'Over Budget by',
    yearlyExpenseBreakdown: 'Yearly Expense Breakdown',
    noExpenseDataForYear: 'No expense data for this year.',
    yearInReview: 'Year In Review',
    
    // Currency Converter
    viewIn: 'View in',
    loading: 'Loading',
    error: 'Error',
    
    // Firebase Not Configured
    firebaseNotConfigured: 'Firebase Not Configured',
    firebaseNotConfiguredMessage: 'This application requires a connection to a Firebase project to function correctly. Please update the <code class="bg-slate-700/50 text-sky-300 p-1 rounded-md">firebase.ts</code> file with your own Firebase project configuration.',
    firebaseOpenFile: 'Open <code class="text-sky-300">firebase.ts</code> and replace the placeholder configuration:',
    firebaseGetValues: 'You can get these values from your Firebase project console under Project settings.',

    // Main App & Toasts
    successMonthCreated: 'New monthly budget created successfully!',
    errorAdBlocker: 'Could not load your {{type}}. This may be due to a browser extension (like an ad-blocker) or a network issue. Please try disabling extensions and check your internet connection.',
    errorCouldNotLoad: 'Could not load your {{type}}. Please check your connection and try again. Error: {{message}}',
    errorCreateBudget: 'Failed to create new budget. Please check your connection and try again.',
    confirmDeleteMonth: 'Are you sure you want to delete this entire month? This action cannot be undone.',
    errorActiveMonth: 'No active month selected. Could not perform action.',
    successExpenseAdded: 'Expense successfully added!',
    errorAddExpense: 'Failed to add expense.',
    successExpenseDeleted: 'Expense deleted.',
    errorDeleteExpense: 'Failed to delete expense.',
    successBudgetsSaved: 'Category budgets saved!',
    errorSaveBudgets: 'Failed to save category budgets.',
    successGoalSet: 'Income goal updated!',
    errorSetGoal: 'Failed to update income goal.',
    successSourceAdded: 'Income source added!',
    errorAddSource: 'Failed to add income source.',
    successSourceUpdated: 'Income source updated!',
    errorUpdateSource: 'Failed to update income source.',
    successSourceDeleted: 'Income source deleted.',
    errorDeleteSource: 'Failed to delete income source.',
    successTransactionAdded: 'Income transaction added.',
    errorAddTransaction: 'Failed to add income transaction.',
    successTransactionDeleted: 'Transaction deleted.',
    errorDeleteTransaction: 'Failed to delete transaction.',
    successTransactionUpdated: 'Transaction status updated.',
    errorUpdateTransaction: 'Failed to update transaction status.',
    successColorsSaved: 'Category colors saved.',
    errorSaveColors: 'Failed to save category colors.',
    successMonthDeleted: 'Monthly budget has been deleted.',
    errorDeleteMonth: 'Failed to delete month.',
    successPaymentConfirmed: 'Payment confirmed successfully!',
    errorConfirmingPayment: 'Error confirming payment.',
    recurringTransactionsUpdated: 'Recurring transactions have been updated.',
    errorProcessingRecurring: 'Failed to process recurring transactions.',
    successRecurringAdded: 'Recurring transaction added.',
    errorRecurringAdd: 'Failed to add recurring transaction.',
    successRecurringDeleted: 'Recurring transaction deleted.',
    errorRecurringDelete: 'Failed to delete recurring transaction.',
    
    // Categories
    category_food: 'Food',
    category_transport: 'Transport',
    category_shopping: 'Shopping',
    category_bills: 'Bills',
    category_entertainment: 'Entertainment',
    category_health: 'Health',
    category_other: 'Other',

    // Income Categories
    incomeCategory_private_lesson: 'Private Lesson',
    incomeCategory_italy_consultancy: 'Italy Consultancy',
    incomeCategory_refunds: 'Refunds',
    incomeCategory_other: 'Other',
  },
  tr: {
    // General
    language_code: 'tr-TR',

    // Auth
    welcomeBack: 'Tekrar Hoş Geldiniz!',
    createAccount: 'Hesap Oluştur',
    signInToDashboard: 'Panonuza erişmek için giriş yapın.',
    getStartedByCreatingAccount: 'Yeni bir hesap oluşturarak başlayın.',
    emailAddress: 'E-posta Adresi',
    password: 'Şifre',
    processing: 'İşleniyor...',
    signIn: 'Giriş Yap',
    orContinueWith: 'Veya şununla devam et',
    signInWithGoogle: 'Google ile Giriş Yap',
    dontHaveAccount: 'Hesabınız yok mu? ',
    alreadyHaveAccount: 'Zaten bir hesabınız var mı? ',
    signUp: 'Kaydol',
    errorFirebaseConfigEmail: 'Yapılandırma hatası. Lütfen Firebase projenizde E-posta/Şifre ile giriş sağlayıcısını etkinleştirin.',
    errorFirebaseConfigGoogle: 'Yapılandırma hatası. Lütfen Firebase projenizde Google ile giriş sağlayıcısını etkinleştirin.',
    errorGoogleSignIn: 'Google ile giriş yapılamadı.',
    errorOccurred: 'Bir hata oluştu.',
    
    // Language Toggle
    changeLanguage: 'Dili değiştir, mevcut dil {{currentLanguage}}',
    language_en: 'English',
    language_tr: 'Türkçe',
    language_it: 'Italiano',
    language_ar: 'العربية',

    // Dashboard
    financialDashboard: 'Finansal Pano',
    welcomeMessage: 'Hoş geldiniz, <span class="font-semibold text-slate-300">{{email}}</span>',
    signOut: 'Çıkış Yap',
    startNewMonthlyBudget: '+ Yeni Aylık Bütçe Başlat',
    welcomeToHub: 'Finans Merkezinize Hoş Geldiniz!',
    noBudgetsYet: "Henüz aylık bir bütçe oluşturmadınız. <br/>Başlamak için yukarıdaki düğmeye tıklayın.",
    viewYearSummary: '{{year}} Özetini Görüntüle',
    budget: 'Bütçe',
    viewDetailsFor: '{{month}} detaylarını görüntüle',
    deleteBudgetFor: '{{month}} bütçesini sil',

    // Monthly Setup
    newMonthlyBudget: 'Yeni Aylık Bütçe',
    setBudgetForNewMonth: 'Yeni bir ay için bütçenizi belirleyin.',
    year: 'Yıl',
    month: 'Ay',
    monthlyBudgetLimit: 'Aylık Bütçe Limiti',
    baseMonthlyIncome: 'Aylık Taban Gelir',
    monthlyIncomeGoalOptional: 'Aylık Gelir Hedefi (İsteğe Bağlı)',
    monthlyIncomeGoal: 'Aylık Gelir Hedefi',
    currency: 'Para Birimi',
    cancel: 'İptal',
    creating: 'Oluşturuluyor...',
    createBudget: 'Bütçe Oluştur',
    errorMonthExists: '{{monthId}} için zaten bir bütçe mevcut.',
    errorInvalidLimit: 'Lütfen bütçe limiti için geçerli, pozitif bir sayı girin.',
    errorInvalidIncome: 'Lütfen gelir için geçerli, negatif olmayan bir sayı girin.',
    errorInvalidIncomeGoal: 'Lütfen gelir hedefi için geçerli, negatif olmayan bir sayı girin.',
    eg1000: 'ör. 1000',
    eg3000: 'ör. 3000',
    eg4000: 'ör. 4000',
    
    // Limit Setter (Initial Setup)
    welcome: 'Hoş geldiniz!',
    setMonthlyBudgetPrompt: 'Başlamak için aylık bütçenizi belirleyin.',
    monthlyIncome: 'Aylık Gelir',
    settingUp: 'Kuruluyor...',
    startTracking: 'Takibe Başla',

    // Monthly View
    dashboard: 'Pano',
    export: 'Dışa Aktar',
    expenses: 'Harcamalar',
    trend: 'Trend',
    categories: 'Kategoriler',
    income: 'Gelir',
    incomeTrend: 'Gelir Trendi',
    recurring: 'Tekrarlayan',
    aiAdvisor: 'YZ Danışman',

    // Summary
    totalSpent: 'Toplam Harcama',
    remainingBudget: 'Kalan Bütçe',
    limit: 'Limit',
    completedIncome: 'Tamamlanan Gelir',
    editGoal: 'Hedefi Düzenle',
    setGoal: 'Hedef Belirle',
    setIncomeGoal: 'Gelir hedefi belirle',
    saveIncomeGoal: 'Gelir hedefini kaydet',
    cancelEditIncomeGoal: 'Gelir hedefi düzenlemesini iptal et',
    goal: 'Hedef',
    noGoalSet: 'Hedef belirlenmemiş.',
    pendingIncome: 'Bekleyen Gelir',
    potentialTotalIncome: 'Potansiyel toplam gelir',
    categorySpending: 'Kategori Harcamaları',
    editBudgets: 'Bütçeleri Düzenle',
    setBudgets: 'Bütçe Belirle',
    setCategoryBudgetsAndColors: 'Kategori Bütçeleri ve Renkleri Ayarla',
    setColorFor: '{{categoryName}} için renk ayarla',
    colorPickerFor: '{{categoryName}} için renk seçici',
    overAllocatedBy: 'Fazla Tahsis:',
    remainingToAllocate: 'Tahsis Edilecek Kalan:',
    allocated: 'Tahsis Edildi',
    saving: 'Kaydediliyor...',
    saveBudgets: 'Bütçeleri Kaydet',
    noCategoryBudgetsSet: "Kategori bütçesi belirlenmemiş. Harcama limitinizi tahsis etmek için 'Bütçe Belirle'ye tıklayın.",
    aiFinancialSummary: 'Yapay Zeka Finansal Özet',
    analyzing: 'Analiz ediliyor...',
    getAnalysis: 'Analiz Al',
    
    // Add Expense Form
    addNewExpense: 'Yeni Harcama Ekle',
    amount: 'Tutar',
    description: 'Açıklama',
    paymentMethod: 'Ödeme Yöntemi',
    cash: 'Nakit',
    card: 'Kart',
    category: 'Kategori',
    addExpense: 'Harcama Ekle',
    adding: 'Ekleniyor...',
    egCoffeeWithFriends: 'ör. Arkadaşlarla kahve',
    errorInvalidAmount: 'Lütfen geçerli, pozitif bir tutar girin.',
    errorEmptyDescription: 'Açıklama boş olamaz.',
    errorSelectCategory: 'Lütfen bir kategori seçin.',
    payInInstallments: 'Taksitli Öde',
    numberOfInstallments: 'Taksit Sayısı',
    errorInvalidInstallments: 'Lütfen geçerli bir taksit sayısı girin (en az 2).',
    scanReceipt: 'Fişi Tara',
    uploadReceipt: 'Fiş yükle',

    // Expense List
    recentExpenses: 'Son Harcamalar',
    searchExpenses: 'Harcama Ara',
    searchByDescription: 'Açıklamaya göre ara...',
    noExpensesAdded: 'Henüz harcama eklenmemiş.',
    noExpensesMatchSearch: 'Aramanızla eşleşen harcama bulunamadı.',
    paidBy: 'Ödeme: {{method}}',
    deleteExpenseFor: '{{description}} harcamasını sil',
    installmentLabel: '{{current}}. Taksit / {{total}}',
    confirmPayment: 'Ödemeyi Onayla',
    paid: 'Ödendi',

    // Category View
    spendingByCategory: 'Kategoriye Göre Harcama',
    percentageOfTotal: 'Toplamın %{{percentage}}',
    categoryTotals: 'Kategori Toplamları (Değiştirmek için tıkla)',
    grandTotal: 'Genel Toplam',
    noDataToDisplay: 'Görüntülenecek veri yok.',
    
    // Income View
    displayingIn: '<strong>{{code}}</strong> olarak görüntüleniyor. Kur: 1 {{baseCode}} = {{rate}} {{code}}',
    addNewIncomeSource: 'Yeni Gelir Kaynağı Ekle',
    sourceName: 'Kaynak Adı',
    egLessonWithAlex: 'ör. Alex ile ders',
    incomeSourceName: 'Gelir Kaynağı Adı',
    incomeSourceAmount: 'Gelir Kaynağı Tutarı',
    addSource: 'Kaynak Ekle',
    yourIncomeSources: 'Gelir Kaynaklarınız',
    quickAddPrompt: 'Hızlıca bekleyen bir işlem ekleyin veya kaynaklarınızı yönetin.',
    transactionDate: 'İşlem Tarihi',
    noIncomeSources: 'Henüz gelir kaynağı tanımlanmamış.',
    editSourceName: 'Kaynak Adını Düzenle',
    editSourceCategory: 'Kaynak Kategorisini Düzenle',
    editSourceAmount: 'Kaynak Tutarını Düzenle',
    save: 'Kaydet',
    fromAmount: 'kaynak {{symbol}}{{amount}}',
    addIncomeFrom: '{{name}} kaynağından gelir ekle',
    editSource: '{{name}} kaynağını düzenle',
    deleteSource: '{{name}} kaynağını sil',
    recentIncomeTransactions: 'Son Gelir İşlemleri',
    noIncomeRecorded: 'Henüz gelir kaydedilmemiş.',
    pending: 'Beklemede',
    markAsPaid: '{{name}} adlı işlemi ödendi olarak işaretle',
    deleteTransactionFor: '{{name}} için işlemi sil',
    completed: 'Tamamlandı',
    errorEnterSourceName: 'Lütfen bir kaynak adı girin.',
    errorInvalidDate: 'Lütfen işlem için geçerli bir tarih seçin.',
    confirmDeleteSource: '"{{name}}" adlı gelir kaynağını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    
    // Recurring View
    manageRecurring: 'Tekrarlayan İşlemleri Yönet',
    addRecurring: 'Tekrarlayan İşlem Ekle',
    transactionType: 'İşlem Türü',
    startDate: 'Başlangıç Tarihi',
    add: 'Ekle',
    noRecurringTransactions: 'Henüz tekrarlayan işlem oluşturulmamış.',
    confirmDeleteRecurring: 'Bu tekrarlayan işlemi silmek istediğinizden emin misiniz? Gelecekte otomatik olarak eklenmeyecektir.',
    nextOn: 'Sıradaki: {{date}}',
    recurringExpenses: 'Tekrarlayan Giderler',
    recurringIncomes: 'Tekrarlayan Gelirler',
    
    // AI Advisor View
    aiFinancialAdvisor: 'Yapay Zeka Finansal Danışmanı',
    aiAdvisorDescription: 'Harcamalarınıza göre mali durumunuzu nasıl yöneteceğiniz ve tasarruf edeceğiniz konusunda kişiselleştirilmiş tavsiyeler isteyin.',
    aiAdvisorPlaceholder: 'ör. Gıda harcamalarımı nasıl azaltabilirim?',
    getAdvice: 'Tavsiye Al',
    errorAiAdvice: 'Üzgünüm, şu anda tavsiye oluşturamadım.',
    errorAiAnalysis: 'Üzgünüm, şu anda bir analiz oluşturamadım. Lütfen daha sonra tekrar deneyin.',

    // Trend Views
    cumulativeSpendingTrend: 'Kümülatif Harcama Trendi',
    cumulativeIncomeTrend: 'Kümülatif Gelir Trendi',
    day: 'Gün',
    cumulative: 'Kümülatif',
    noExpenseDataForTrend: 'Trendi görüntülemek için harcama verisi yok.',
    noCompletedIncomeForTrend: 'Trendi görüntülemek için tamamlanmış gelir verisi yok.',

    // Comparison View
    thisMonthVsLastMonth: 'Bu Ay vs. Geçen Ay',
    cumulativeSpendingComparison: 'Kümülatif Harcama Karşılaştırması',
    dayOfMonth: 'Ayın Günü',
    
    // Annual View
    annualSummary: '{{year}} Yıllık Özet',
    viewYear: 'Yılı Görüntüle',
    previousYear: 'Önceki yıl',
    nextYear: 'Sonraki yıl',
    selectYearToView: 'Yıllık özeti görüntülemek için yıl seçin',
    totalIncome: 'Toplam Gelir',
    totalExpenses: 'Toplam Harcamalar',
    netBalance: 'Net Bakiye',
    net: 'Net',
    monthlyFinancialOverview: 'Aylık Finansal Genel Bakış',
    underBudgetBy: 'Bütçe Altında',
    overBudgetBy: 'Bütçe Üstünde',
    yearlyExpenseBreakdown: 'Yıllık Harcama Dağılımı',
    noExpenseDataForYear: 'Bu yıl için harcama verisi yok.',
    yearInReview: 'Yıl Değerlendirmesi',

    // Currency Converter
    viewIn: 'Görünüm',
    loading: 'Yükleniyor',
    error: 'Hata',
    
    // Firebase Not Configured
    firebaseNotConfigured: 'Firebase Yapılandırılmamış',
    firebaseNotConfiguredMessage: 'Bu uygulamanın düzgün çalışması için bir Firebase projesine bağlanması gerekir. Lütfen <code class="bg-slate-700/50 text-sky-300 p-1 rounded-md">firebase.ts</code> dosyasını kendi Firebase proje yapılandırmanızla güncelleyin.',
    firebaseOpenFile: '<code class="text-sky-300">firebase.ts</code> dosyasını açın ve yer tutucu yapılandırmayı değiştirin:',
    firebaseGetValues: 'Bu değerleri Firebase proje konsolunuzdaki Proje ayarlarından alabilirsiniz.',

    // Main App & Toasts
    successMonthCreated: 'Yeni aylık bütçe başarıyla oluşturuldu!',
    errorAdBlocker: '{{type}} yüklenemedi. Bu, bir tarayıcı eklentisinden (reklam engelleyici gibi) veya bir ağ sorunundan kaynaklanıyor olabilir. Lütfen eklentileri devre dışı bırakmayı deneyin ve internet bağlantınızı kontrol edin.',
    errorCouldNotLoad: '{{type}} yüklenemedi. Lütfen bağlantınızı kontrol edip tekrar deneyin. Hata: {{message}}',
    errorCreateBudget: 'Yeni bütçe oluşturulamadı. Lütfen bağlantınızı kontrol edip tekrar deneyin.',
    confirmDeleteMonth: 'Bu ayın tamamını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    errorActiveMonth: 'Aktif ay seçili değil. İşlem gerçekleştirilemedi.',
    successExpenseAdded: 'Harcama başarıyla eklendi!',
    errorAddExpense: 'Harcama eklenemedi.',
    successExpenseDeleted: 'Harcama silindi.',
    errorDeleteExpense: 'Harcama silinemedi.',
    successBudgetsSaved: 'Kategori bütçeleri kaydedildi!',
    errorSaveBudgets: 'Kategori bütçeleri kaydedilemedi.',
    successGoalSet: 'Gelir hedefi güncellendi!',
    errorSetGoal: 'Gelir hedefi güncellenemedi.',
    successSourceAdded: 'Gelir kaynağı eklendi!',
    errorAddSource: 'Gelir kaynağı eklenemedi.',
    successSourceUpdated: 'Gelir kaynağı güncellendi!',
    errorUpdateSource: 'Gelir kaynağı güncellenemedi.',
    successSourceDeleted: 'Gelir kaynağı silindi.',
    errorDeleteSource: 'Gelir kaynağı silinemedi.',
    successTransactionAdded: 'Gelir işlemi eklendi.',
    errorAddTransaction: 'Gelir işlemi eklenemedi.',
    successTransactionDeleted: 'İşlem silindi.',
    errorDeleteTransaction: 'İşlem silinemedi.',
    successTransactionUpdated: 'İşlem durumu güncellendi.',
    errorUpdateTransaction: 'İşlem durumu güncellenemedi.',
    successColorsSaved: 'Kategori renkleri kaydedildi.',
    errorSaveColors: 'Kategori renkleri kaydedilemedi.',
    successMonthDeleted: 'Aylık bütçe silindi.',
    errorDeleteMonth: 'Aylık bütçe silinemedi.',
    successPaymentConfirmed: 'Ödeme başarıyla onaylandı!',
    errorConfirmingPayment: 'Ödeme onaylanırken bir hata oluştu.',
    recurringTransactionsUpdated: 'Tekrarlayan işlemler güncellendi.',
    errorProcessingRecurring: 'Tekrarlayan işlemler işlenemedi.',
    successRecurringAdded: 'Tekrarlayan işlem eklendi.',
    errorRecurringAdd: 'Tekrarlayan işlem eklenemedi.',
    successRecurringDeleted: 'Tekrarlayan işlem silindi.',
    errorRecurringDelete: 'Tekrarlayan işlem silinemedi.',


    // Categories
    category_food: 'Gıda',
    category_transport: 'Ulaşım',
    category_shopping: 'Alışveriş',
    category_bills: 'Faturalar',
    category_entertainment: 'Eğlence',
    category_health: 'Sağlık',
    category_other: 'Diğer',

    // Income Categories
    incomeCategory_private_lesson: 'Özel Ders',
    incomeCategory_italy_consultancy: 'İtalya Danışmanlık',
    incomeCategory_refunds: 'İadeler',
    incomeCategory_other: 'Diğer',
  },
  it: {
    // General
    language_code: 'it-IT',

    // Auth
    welcomeBack: 'Bentornato!',
    createAccount: 'Crea Account',
    signInToDashboard: 'Accedi per visualizzare la tua dashboard.',
    getStartedByCreatingAccount: 'Inizia creando un nuovo account.',
    emailAddress: 'Indirizzo Email',
    password: 'Password',
    processing: 'In elaborazione...',
    signIn: 'Accedi',
    orContinueWith: 'Oppure continua con',
    signInWithGoogle: 'Accedi con Google',
    dontHaveAccount: "Non hai un account? ",
    alreadyHaveAccount: 'Hai già un account? ',
    signUp: 'Registrati',
    errorFirebaseConfigEmail: 'Errore di configurazione. Abilita il provider di accesso Email/Password nel tuo progetto Firebase.',
    errorFirebaseConfigGoogle: 'Errore di configurazione. Abilita il provider di accesso Google nel tuo progetto Firebase.',
    errorGoogleSignIn: 'Accesso con Google non riuscito.',
    errorOccurred: 'Si è verificato un errore.',
    
    // Language Toggle
    changeLanguage: 'Cambia lingua, corrente è {{currentLanguage}}',
    language_en: 'English',
    language_tr: 'Türkçe',
    language_it: 'Italiano',
    language_ar: 'العربية',

    // Dashboard
    financialDashboard: 'Dashboard Finanziaria',
    welcomeMessage: 'Benvenuto, <span class="font-semibold text-slate-300">{{email}}</span>',
    signOut: 'Esci',
    startNewMonthlyBudget: '+ Inizia Nuovo Budget Mensile',
    welcomeToHub: 'Benvenuto nel Tuo Hub Finanziario!',
    noBudgetsYet: "Non hai ancora impostato alcun budget mensile. <br/>Clicca il pulsante qui sopra per iniziare.",
    viewYearSummary: 'Vedi Riepilogo {{year}}',
    budget: 'Budget',
    viewDetailsFor: 'Vedi dettagli per {{month}}',
    deleteBudgetFor: 'Elimina budget per {{month}}',
    
    // Monthly Setup
    newMonthlyBudget: 'Nuovo Budget Mensile',
    setBudgetForNewMonth: 'Imposta il tuo budget per un nuovo mese.',
    year: 'Anno',
    month: 'Mese',
    monthlyBudgetLimit: 'Limite Budget Mensile',
    baseMonthlyIncome: 'Reddito Mensile di Base',
    monthlyIncomeGoalOptional: 'Obiettivo di Reddito Mensile (Opzionale)',
    monthlyIncomeGoal: 'Obiettivo di Reddito Mensile',
    currency: 'Valuta',
    cancel: 'Annulla',
    creating: 'Creazione in corso...',
    createBudget: 'Crea Budget',
    errorMonthExists: 'Esiste già un budget per {{monthId}}.',
    errorInvalidLimit: 'Inserisci un numero valido e positivo per il limite di budget.',
    errorInvalidIncome: 'Inserisci un numero valido e non negativo per il reddito.',
    errorInvalidIncomeGoal: 'Inserisci un numero valido e non negativo per l\'obiettivo di reddito.',
    eg1000: 'es. 1000',
    eg3000: 'es. 3000',
    eg4000: 'es. 4000',

    // Limit Setter (Initial Setup)
    welcome: 'Benvenuto!',
    setMonthlyBudgetPrompt: 'Imposta il tuo budget mensile per iniziare.',
    monthlyIncome: 'Reddito Mensile',
    settingUp: 'Impostazione...',
    startTracking: 'Inizia a Tracciare',

    // Monthly View
    dashboard: 'Dashboard',
    export: 'Esporta',
    expenses: 'Spese',
    trend: 'Andamento',
    categories: 'Categorie',
    income: 'Entrate',
    incomeTrend: 'Andamento Entrate',
    recurring: 'Ricorrenti',
    aiAdvisor: 'Consulente AI',

    // Summary
    totalSpent: 'Spesa Totale',
    remainingBudget: 'Budget Rimanente',
    limit: 'Limite',
    completedIncome: 'Entrate Completate',
    editGoal: 'Modifica Obiettivo',
    setGoal: 'Imposta Obiettivo',
    setIncomeGoal: 'Imposta obiettivo di reddito',
    saveIncomeGoal: 'Salva obiettivo di reddito',
    cancelEditIncomeGoal: 'Annulla modifica obiettivo di reddito',
    goal: 'Obiettivo',
    noGoalSet: 'Nessun obiettivo impostato.',
    pendingIncome: 'Entrate in Sospeso',
    potentialTotalIncome: 'Reddito totale potenziale',
    categorySpending: 'Spesa per Categoria',
    editBudgets: 'Modifica Budget',
    setBudgets: 'Imposta Budget',
    setCategoryBudgetsAndColors: 'Imposta Budget e Colori Categorie',
    setColorFor: 'Imposta colore per {{categoryName}}',
    colorPickerFor: 'Selettore colore per {{categoryName}}',
    overAllocatedBy: 'Superato di:',
    remainingToAllocate: 'Rimanente da Allocare:',
    allocated: 'Allocato',
    saving: 'Salvataggio...',
    saveBudgets: 'Salva Budget',
    noCategoryBudgetsSet: "Nessun budget di categoria impostato. Clicca 'Imposta Budget' per allocare il tuo limite di spesa.",
    aiFinancialSummary: 'Riepilogo Finanziario AI',
    analyzing: 'Analisi in corso...',
    getAnalysis: 'Ottieni Analisi',

    // Add Expense Form
    addNewExpense: 'Aggiungi Nuova Spesa',
    amount: 'Importo',
    description: 'Descrizione',
    paymentMethod: 'Metodo di Pagamento',
    cash: 'Contanti',
    card: 'Carta',
    category: 'Categoria',
    addExpense: 'Aggiungi Spesa',
    adding: 'Aggiunta...',
    egCoffeeWithFriends: 'es. Caffè con amici',
    errorInvalidAmount: 'Inserisci un importo valido e positivo.',
    errorEmptyDescription: 'La descrizione non può essere vuota.',
    errorSelectCategory: 'Seleziona una categoria.',
    payInInstallments: 'Paga a rate',
    numberOfInstallments: 'Numero di rate',
    errorInvalidInstallments: 'Inserisci un numero di rate valido (minimo 2).',
    scanReceipt: 'Scansiona Ricevuta',
    uploadReceipt: 'Carica una ricevuta',

    // Expense List
    recentExpenses: 'Spese Recenti',
    searchExpenses: 'Cerca Spese',
    searchByDescription: 'Cerca per descrizione...',
    noExpensesAdded: 'Nessuna spesa ancora aggiunta.',
    noExpensesMatchSearch: 'Nessuna spesa corrisponde alla tua ricerca.',
    paidBy: 'Pagato con {{method}}',
    deleteExpenseFor: 'Elimina spesa per {{description}}',
    installmentLabel: 'Rata {{current}}/{{total}}',
    confirmPayment: 'Conferma Pagamento',
    paid: 'Pagato',

    // Category View
    spendingByCategory: 'Spesa per Categoria',
    percentageOfTotal: '{{percentage}}% del totale',
    categoryTotals: 'Totali Categoria (Clicca per mostrare/nascondere)',
    grandTotal: 'Totale Generale',
    noDataToDisplay: 'Nessun dato da visualizzare.',

    // Income View
    displayingIn: 'Visualizzazione in <strong>{{code}}</strong>. Tasso: 1 {{baseCode}} = {{rate}} {{code}}',
    addNewIncomeSource: 'Aggiungi Nuova Fonte di Reddito',
    sourceName: 'Nome Fonte',
    egLessonWithAlex: 'es. Lezione con Alex',
    incomeSourceName: 'Nome Fonte di Reddito',
    incomeSourceAmount: 'Importo Fonte di Reddito',
    addSource: 'Aggiungi Fonte',
    yourIncomeSources: 'Le Tue Fonti di Reddito',
    quickAddPrompt: 'Aggiungi rapidamente una transazione in sospeso o gestisci le tue fonti.',
    transactionDate: 'Data Transazione',
    noIncomeSources: 'Nessuna fonte di reddito ancora definita.',
    editSourceName: 'Modifica Nome Fonte',
    editSourceCategory: 'Modifica Categoria Fonte',
    editSourceAmount: 'Modifica Importo Fonte',
    save: 'Salva',
    fromAmount: 'da {{symbol}}{{amount}}',
    addIncomeFrom: 'Aggiungi entrata da {{name}}',
    editSource: 'Modifica fonte {{name}}',
    deleteSource: 'Elimina fonte {{name}}',
    recentIncomeTransactions: 'Transazioni di Reddito Recenti',
    noIncomeRecorded: 'Nessun reddito ancora registrato.',
    pending: 'In Sospeso',
    markAsPaid: 'Segna transazione da {{name}} come pagata',
    deleteTransactionFor: 'Elimina transazione per {{name}}',
    completed: 'Completato',
    errorEnterSourceName: 'Inserisci un nome per la fonte.',
    errorInvalidDate: 'Seleziona una data valida per la transazione.',
    confirmDeleteSource: 'Sei sicuro di voler eliminare la fonte di reddito "{{name}}"? Questa azione non può essere annullata.',

    // Recurring View
    manageRecurring: 'Gestisci Transazioni Ricorrenti',
    addRecurring: 'Aggiungi Transazione Ricorrente',
    transactionType: 'Tipo di Transazione',
    startDate: 'Data di Inizio',
    add: 'Aggiungi',
    noRecurringTransactions: 'Nessuna transazione ricorrente è stata ancora impostata.',
    confirmDeleteRecurring: 'Sei sicuro di voler eliminare questa transazione ricorrente? Non verrà più aggiunta automaticamente in futuro.',
    nextOn: 'Prossima il: {{date}}',
    recurringExpenses: 'Spese Ricorrenti',
    recurringIncomes: 'Entrate Ricorrenti',

    // AI Advisor View
    aiFinancialAdvisor: 'Consulente Finanziario AI',
    aiAdvisorDescription: 'Chiedi consigli personalizzati su come gestire le tue finanze e risparmiare denaro in base alle tue spese.',
    aiAdvisorPlaceholder: 'es. Come posso ridurre le mie spese alimentari?',
    getAdvice: 'Ottieni Consiglio',
    errorAiAdvice: 'Spiacente, non sono stato in grado di generare consigli in questo momento.',
    errorAiAnalysis: 'Spiacente, non sono riuscito a generare un\'analisi in questo momento. Riprova più tardi.',

    // Trend Views
    cumulativeSpendingTrend: 'Andamento Spesa Cumulativa',
    cumulativeIncomeTrend: 'Andamento Reddito Cumulativo',
    day: 'Giorno',
    cumulative: 'Cumulativo',
    noExpenseDataForTrend: 'Nessun dato di spesa per visualizzare l\'andamento.',
    noCompletedIncomeForTrend: 'Nessun dato di reddito completato per visualizzare l\'andamento.',

    // Comparison View
    thisMonthVsLastMonth: 'Questo Mese vs. Mese Scorso',
    cumulativeSpendingComparison: 'Confronto Spesa Cumulativa',
    dayOfMonth: 'Giorno del Mese',

    // Annual View
    annualSummary: 'Riepilogo Annuale {{year}}',
    viewYear: 'Vedi Anno',
    previousYear: 'Anno precedente',
    nextYear: 'Anno successivo',
    selectYearToView: 'Seleziona l\'anno per vedere il riepilogo annuale',
    totalIncome: 'Entrate Totali',
    totalExpenses: 'Spese Totali',
    netBalance: 'Saldo Netto',
    net: 'Netto',
    monthlyFinancialOverview: 'Panoramica Finanziaria Mensile',
    underBudgetBy: 'Sotto Budget di',
    overBudgetBy: 'Sopra Budget di',
    yearlyExpenseBreakdown: 'Dettaglio Spese Annuali',
    noExpenseDataForYear: 'Nessun dato di spesa per quest\'anno.',
    yearInReview: 'Revisione dell\'Anno',
    
    // Currency Converter
    viewIn: 'Vedi in',
    loading: 'Caricamento',
    error: 'Errore',
    
    // Firebase Not Configured
    firebaseNotConfigured: 'Firebase non Configurato',
    firebaseNotConfiguredMessage: 'Questa applicazione richiede una connessione a un progetto Firebase per funzionare correttamente. Aggiorna il file <code class="bg-slate-700/50 text-sky-300 p-1 rounded-md">firebase.ts</code> con la configurazione del tuo progetto Firebase.',
    firebaseOpenFile: 'Apri <code class="text-sky-300">firebase.ts</code> e sostituisci la configurazione segnaposto:',
    firebaseGetValues: 'Puoi ottenere questi valori dalla console del tuo progetto Firebase sotto Impostazioni Progetto.',

    // Main App & Toasts
    successMonthCreated: 'Nuovo budget mensile creato con successo!',
    errorAdBlocker: 'Impossibile caricare i tuoi {{type}}. Ciò potrebbe essere dovuto a un\'estensione del browser (come un ad-blocker) o a un problema di rete. Prova a disabilitare le estensioni e controlla la tua connessione internet.',
    errorCouldNotLoad: 'Impossibile caricare i tuoi {{type}}. Controlla la tua connessione e riprova. Errore: {{message}}',
    errorCreateBudget: 'Creazione nuovo budget non riuscita. Controlla la tua connessione e riprova.',
    confirmDeleteMonth: 'Sei sicuro di voler eliminare questo intero mese? Questa azione non può essere annullata.',
    errorActiveMonth: 'Nessun mese attivo selezionato. Impossibile eseguire l\'azione.',
    successExpenseAdded: 'Spesa aggiunta con successo!',
    errorAddExpense: 'Aggiunta spesa non riuscita.',
    successExpenseDeleted: 'Spesa eliminata.',
    errorDeleteExpense: 'Eliminazione spesa non riuscita.',
    successBudgetsSaved: 'Budget delle categorie salvati!',
    errorSaveBudgets: 'Salvataggio budget delle categorie non riuscito.',
    successGoalSet: 'Obiettivo di reddito aggiornato!',
    errorSetGoal: 'Aggiornamento obiettivo di reddito non riuscito.',
    successSourceAdded: 'Fonte di reddito aggiunta!',
    errorAddSource: 'Aggiunta fonte di reddito non riuscita.',
    successSourceUpdated: 'Fonte di reddito aggiornata!',
    errorUpdateSource: 'Aggiornamento fonte di reddito non riuscito.',
    successSourceDeleted: 'Fonte di reddito eliminata.',
    errorDeleteSource: 'Eliminazione fonte di reddito non riuscita.',
    successTransactionAdded: 'Transazione di reddito aggiunta.',
    errorAddTransaction: 'Aggiunta transazione di reddito non riuscita.',
    successTransactionDeleted: 'Transazione eliminata.',
    errorDeleteTransaction: 'Eliminazione transazione non riuscita.',
    successTransactionUpdated: 'Stato transazione aggiornato.',
    errorUpdateTransaction: 'Aggiornamento stato transazione non riuscito.',
    successColorsSaved: 'Colori delle categorie salvati.',
    errorSaveColors: 'Salvataggio colori delle categorie non riuscito.',
    successMonthDeleted: 'Il budget mensile è stato eliminato.',
    errorDeleteMonth: 'Eliminazione del mese non riuscita.',
    successPaymentConfirmed: 'Pagamento confermato con successo!',
    errorConfirmingPayment: 'Errore durante la conferma del pagamento.',
    recurringTransactionsUpdated: 'Le transazioni ricorrenti sono state aggiornate.',
    errorProcessingRecurring: 'Elaborazione delle transazioni ricorrenti non riuscita.',
    successRecurringAdded: 'Transazione ricorrente aggiunta.',
    errorRecurringAdd: 'Aggiunta della transazione ricorrente non riuscita.',
    successRecurringDeleted: 'Transazione ricorrente eliminata.',
    errorRecurringDelete: 'Eliminazione della transazione ricorrente non riuscita.',
    
    // Categories
    category_food: 'Cibo',
    category_transport: 'Trasporti',
    category_shopping: 'Shopping',
    category_bills: 'Bollette',
    category_entertainment: 'Intrattenimento',
    category_health: 'Salute',
    category_other: 'Altro',

    // Income Categories
    incomeCategory_private_lesson: 'Lezione Privata',
    incomeCategory_italy_consultancy: 'Consulenza Italia',
    incomeCategory_refunds: 'Rimborsi',
    incomeCategory_other: 'Altro',
  },
  ar: {
    // General
    language_code: 'ar-SA',

    // Auth
    welcomeBack: 'أهلاً بعودتك!',
    createAccount: 'إنشاء حساب',
    signInToDashboard: 'سجل الدخول للوصول إلى لوحة التحكم الخاصة بك.',
    getStartedByCreatingAccount: 'ابدأ بإنشاء حساب جديد.',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    processing: 'جارٍ المعالجة...',
    signIn: 'تسجيل الدخول',
    orContinueWith: 'أو المتابعة باستخدام',
    signInWithGoogle: 'تسجيل الدخول باستخدام جوجل',
    dontHaveAccount: 'ليس لديك حساب؟ ',
    alreadyHaveAccount: 'لديك حساب بالفعل؟ ',
    signUp: 'انشاء حساب',
    errorFirebaseConfigEmail: 'خطأ في الإعداد. يرجى تمكين مزود تسجيل الدخول بالبريد الإلكتروني/كلمة المرور في مشروع Firebase الخاص بك.',
    errorFirebaseConfigGoogle: 'خطأ في الإعداد. يرجى تمكين مزود تسجيل الدخول بجوجل في مشروع Firebase الخاص بك.',
    errorGoogleSignIn: 'فشل تسجيل الدخول باستخدام جوجل.',
    errorOccurred: 'حدث خطأ ما.',
    
    // Language Toggle
    changeLanguage: 'تغيير اللغة، الحالية هي {{currentLanguage}}',
    language_en: 'English',
    language_tr: 'Türkçe',
    language_it: 'Italiano',
    language_ar: 'العربية',

    // Dashboard
    financialDashboard: 'لوحة التحكم المالية',
    welcomeMessage: 'أهلاً بك، <span class="font-semibold text-slate-300">{{email}}</span>',
    signOut: 'تسجيل الخروج',
    startNewMonthlyBudget: '+ بدء ميزانية شهرية جديدة',
    welcomeToHub: 'أهلاً بك في مركزك المالي!',
    noBudgetsYet: "لم تقم بإعداد أي ميزانيات شهرية بعد. <br/>انقر على الزر أعلاه للبدء.",
    viewYearSummary: 'عرض ملخص {{year}}',
    budget: 'الميزانية',
    viewDetailsFor: 'عرض تفاصيل شهر {{month}}',
    deleteBudgetFor: 'حذف ميزانية شهر {{month}}',
    
    // Monthly Setup
    newMonthlyBudget: 'ميزانية شهرية جديدة',
    setBudgetForNewMonth: 'حدد ميزانيتك لشهر جديد.',
    year: 'السنة',
    month: 'الشهر',
    monthlyBudgetLimit: 'حد الميزانية الشهرية',
    baseMonthlyIncome: 'الدخل الشهري الأساسي',
    monthlyIncomeGoalOptional: 'هدف الدخل الشهري (اختياري)',
    monthlyIncomeGoal: 'هدف الدخل الشهري',
    currency: 'العملة',
    cancel: 'إلغاء',
    creating: 'جارٍ الإنشاء...',
    createBudget: 'إنشاء الميزانية',
    errorMonthExists: 'توجد ميزانية بالفعل لشهر {{monthId}}.',
    errorInvalidLimit: 'الرجاء إدخال رقم موجب صالح لحد الميزانية.',
    errorInvalidIncome: 'الرجاء إدخال رقم صالح وغير سالب للدخل.',
    errorInvalidIncomeGoal: 'الرجاء إدخال رقم صالح وغير سالب لهدف الدخل.',
    eg1000: 'مثال: 1000',
    eg3000: 'مثال: 3000',
    eg4000: 'مثال: 4000',

    // Limit Setter (Initial Setup)
    welcome: 'أهلاً بك!',
    setMonthlyBudgetPrompt: 'حدد ميزانيتك الشهرية للبدء.',
    monthlyIncome: 'الدخل الشهري',
    settingUp: 'جارٍ الإعداد...',
    startTracking: 'ابدأ التتبع',

    // Monthly View
    dashboard: 'لوحة التحكم',
    export: 'تصدير',
    expenses: 'المصروفات',
    trend: 'الاتجاه',
    categories: 'الفئات',
    income: 'الدخل',
    incomeTrend: 'اتجاه الدخل',
    recurring: 'متكرر',
    aiAdvisor: 'مستشار ذكاء اصطناعي',

    // Summary
    totalSpent: 'إجمالي المصروفات',
    remainingBudget: 'الميزانية المتبقية',
    limit: 'الحد',
    completedIncome: 'الدخل المكتمل',
    editGoal: 'تعديل الهدف',
    setGoal: 'تحديد الهدف',
    setIncomeGoal: 'تحديد هدف الدخل',
    saveIncomeGoal: 'حفظ هدف الدخل',
    cancelEditIncomeGoal: 'إلغاء تعديل هدف الدخل',
    goal: 'الهدف',
    noGoalSet: 'لم يتم تحديد هدف.',
    pendingIncome: 'الدخل المعلق',
    potentialTotalIncome: 'إجمالي الدخل المحتمل',
    categorySpending: 'الإنفاق حسب الفئة',
    editBudgets: 'تعديل الميزانيات',
    setBudgets: 'تحديد الميزانيات',
    setCategoryBudgetsAndColors: 'تحديد ميزانيات وألوان الفئات',
    setColorFor: 'تحديد لون لـ {{categoryName}}',
    colorPickerFor: 'منتقي الألوان لـ {{categoryName}}',
    overAllocatedBy: 'تم التجاوز بمقدار:',
    remainingToAllocate: 'المتبقي للتخصيص:',
    allocated: 'المخصص',
    saving: 'جارٍ الحفظ...',
    saveBudgets: 'حفظ الميزانيات',
    noCategoryBudgetsSet: "لم يتم تحديد ميزانيات للفئات. انقر على 'تحديد الميزانيات' لتخصيص حد الإنفاق الخاص بك.",
    aiFinancialSummary: 'ملخص مالي بالذكاء الاصطناعي',
    analyzing: 'جارٍ التحليل...',
    getAnalysis: 'احصل على تحليل',

    // Add Expense Form
    addNewExpense: 'إضافة مصروف جديد',
    amount: 'المبلغ',
    description: 'الوصف',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقداً',
    card: 'بطاقة',
    category: 'الفئة',
    addExpense: 'إضافة مصروف',
    adding: 'جارٍ الإضافة...',
    egCoffeeWithFriends: 'مثال: قهوة مع الأصدقاء',
    errorInvalidAmount: 'الرجاء إدخال مبلغ موجب صالح.',
    errorEmptyDescription: 'لا يمكن أن يكون الوصف فارغًا.',
    errorSelectCategory: 'الرجاء تحديد فئة.',
    payInInstallments: 'الدفع بالأقساط',
    numberOfInstallments: 'عدد الأقساط',
    errorInvalidInstallments: 'الرجاء إدخال عدد صالح من الأقساط (2 كحد أدنى).',
    scanReceipt: 'مسح الإيصال',
    uploadReceipt: 'تحميل إيصال',

    // Expense List
    recentExpenses: 'المصروفات الأخيرة',
    searchExpenses: 'بحث في المصروفات',
    searchByDescription: 'بحث حسب الوصف...',
    noExpensesAdded: 'لم تتم إضافة أي مصروفات بعد.',
    noExpensesMatchSearch: 'لا توجد مصروفات تطابق بحثك.',
    paidBy: 'تم الدفع بواسطة {{method}}',
    deleteExpenseFor: 'حذف مصروف لـ {{description}}',
    installmentLabel: 'القسط {{current}}/{{total}}',
    confirmPayment: 'تأكيد الدفع',
    paid: 'مدفوع',

    // Category View
    spendingByCategory: 'الإنفاق حسب الفئة',
    percentageOfTotal: '{{percentage}}% من الإجمالي',
    categoryTotals: 'إجماليات الفئات (انقر للتبديل)',
    grandTotal: 'المجموع الإجمالي',
    noDataToDisplay: 'لا توجد بيانات لعرضها.',

    // Income View
    displayingIn: 'العرض بعملة <strong>{{code}}</strong>. السعر: 1 {{baseCode}} = {{rate}} {{code}}',
    addNewIncomeSource: 'إضافة مصدر دخل جديد',
    sourceName: 'اسم المصدر',
    egLessonWithAlex: 'مثال: درس مع أليكس',
    incomeSourceName: 'اسم مصدر الدخل',
    incomeSourceAmount: 'مبلغ مصدر الدخل',
    addSource: 'إضافة مصدر',
    yourIncomeSources: 'مصادر دخلك',
    quickAddPrompt: 'أضف بسرعة معاملة معلقة أو قم بإدارة مصادرك.',
    transactionDate: 'تاريخ المعاملة',
    noIncomeSources: 'لم يتم تحديد مصادر دخل بعد.',
    editSourceName: 'تعديل اسم المصدر',
    editSourceCategory: 'تعديل فئة المصدر',
    editSourceAmount: 'تعديل مبلغ المصدر',
    save: 'حفظ',
    fromAmount: 'من {{symbol}}{{amount}}',
    addIncomeFrom: 'إضافة دخل من {{name}}',
    editSource: 'تعديل المصدر {{name}}',
    deleteSource: 'حذف المصدر {{name}}',
    recentIncomeTransactions: 'معاملات الدخل الأخيرة',
    noIncomeRecorded: 'لم يتم تسجيل أي دخل بعد.',
    pending: 'معلق',
    markAsPaid: 'تمييز معاملة من {{name}} كمدفوعة',
    deleteTransactionFor: 'حذف معاملة لـ {{name}}',
    completed: 'مكتمل',
    errorEnterSourceName: 'الرجاء إدخال اسم المصدر.',
    errorInvalidDate: 'الرجاء تحديد تاريخ صالح للمعاملة.',
    confirmDeleteSource: 'هل أنت متأكد من أنك تريد حذف مصدر الدخل "{{name}}؟" لا يمكن التراجع عن هذا الإجراء.',

    // Recurring View
    manageRecurring: 'إدارة المعاملات المتكررة',
    addRecurring: 'إضافة معاملة متكررة',
    transactionType: 'نوع المعاملة',
    startDate: 'تاريخ البدء',
    add: 'إضافة',
    noRecurringTransactions: 'لم يتم إعداد أي معاملات متكررة بعد.',
    confirmDeleteRecurring: 'هل أنت متأكد من حذف هذه المعاملة المتكررة؟ لن تتم إضافتها تلقائيًا في المستقبل.',
    nextOn: 'التالي في: {{date}}',
    recurringExpenses: 'المصروفات المتكررة',
    recurringIncomes: 'الدخل المتكرر',

    // AI Advisor View
    aiFinancialAdvisor: 'مستشار مالي بالذكاء الاصطناعي',
    aiAdvisorDescription: 'اطلب نصيحة شخصية حول كيفية إدارة أموالك وتوفير المال بناءً على إنفاقك.',
    aiAdvisorPlaceholder: 'مثال: كيف يمكنني تقليل إنفاقي على الطعام؟',
    getAdvice: 'احصل على نصيحة',
    errorAiAdvice: 'عذراً، لم أتمكن من إنشاء نصيحة في هذا الوقت.',
    errorAiAnalysis: 'عذراً، لم أتمكن من إنشاء تحليل الآن. يرجى المحاولة مرة أخرى لاحقًا.',

    // Trend Views
    cumulativeSpendingTrend: 'الاتجاه التراكمي للإنفاق',
    cumulativeIncomeTrend: 'الاتجاه التراكمي للدخل',
    day: 'يوم',
    cumulative: 'تراكمي',
    noExpenseDataForTrend: 'لا توجد بيانات مصروفات لعرض الاتجاه.',
    noCompletedIncomeForTrend: 'لا توجد بيانات دخل مكتملة لعرض الاتجاه.',

    // Comparison View
    thisMonthVsLastMonth: 'هذا الشهر مقابل الشهر الماضي',
    cumulativeSpendingComparison: 'مقارنة الإنفاق التراكمي',
    dayOfMonth: 'يوم من الشهر',

    // Annual View
    annualSummary: 'ملخص سنوي لعام {{year}}',
    viewYear: 'عرض السنة',
    previousYear: 'السنة السابقة',
    nextYear: 'السنة التالية',
    selectYearToView: 'حدد السنة لعرض الملخص السنوي',
    totalIncome: 'إجمالي الدخل',
    totalExpenses: 'إجمالي المصروفات',
    netBalance: 'صافي الرصيد',
    net: 'الصافي',
    monthlyFinancialOverview: 'نظرة عامة مالية شهرية',
    underBudgetBy: 'أقل من الميزانية بمقدار',
    overBudgetBy: 'أكثر من الميزانية بمقدار',
    yearlyExpenseBreakdown: 'تفصيل المصروفات السنوية',
    noExpenseDataForYear: 'لا توجد بيانات مصروفات لهذه السنة.',
    yearInReview: 'مراجعة السنة',
    
    // Currency Converter
    viewIn: 'عرض بـ',
    loading: 'جارٍ التحميل',
    error: 'خطأ',
    
    // Firebase Not Configured
    firebaseNotConfigured: 'Firebase غير مهيأ',
    firebaseNotConfiguredMessage: 'يتطلب هذا التطبيق الاتصال بمشروع Firebase ليعمل بشكل صحيح. يرجى تحديث ملف <code class="bg-slate-700/50 text-sky-300 p-1 rounded-md">firebase.ts</code> ببيانات مشروع Firebase الخاص بك.',
    firebaseOpenFile: 'افتح <code class="text-sky-300">firebase.ts</code> واستبدل بيانات الإعداد المؤقتة:',
    firebaseGetValues: 'يمكنك الحصول على هذه القيم من وحدة تحكم مشروع Firebase الخاص بك ضمن إعدادات المشروع.',

    // Main App & Toasts
    successMonthCreated: 'تم إنشاء ميزانية شهرية جديدة بنجاح!',
    errorAdBlocker: 'تعذر تحميل {{type}} الخاص بك. قد يكون هذا بسبب امتداد متصفح (مثل مانع الإعلانات) أو مشكلة في الشبكة. يرجى محاولة تعطيل الامتدادات والتحقق من اتصالك بالإنترنت.',
    errorCouldNotLoad: 'تعذر تحميل {{type}}. يرجى التحقق من اتصالك والمحاولة مرة أخرى. خطأ: {{message}}',
    errorCreateBudget: 'فشل في إنشاء ميزانية جديدة. يرجى التحقق من اتصالك والمحاولة مرة أخرى.',
    confirmDeleteMonth: 'هل أنت متأكد من أنك تريد حذف هذا الشهر بأكمله؟ لا يمكن التراجع عن هذا الإجراء.',
    errorActiveMonth: 'لم يتم تحديد شهر نشط. تعذر تنفيذ الإجراء.',
    successExpenseAdded: 'تمت إضافة المصروف بنجاح!',
    errorAddExpense: 'فشل في إضافة المصروف.',
    successExpenseDeleted: 'تم حذف المصروف.',
    errorDeleteExpense: 'فشل في حذف المصروف.',
    successBudgetsSaved: 'تم حفظ ميزانيات الفئات!',
    errorSaveBudgets: 'فشل في حفظ ميزانيات الفئات.',
    successGoalSet: 'تم تحديث هدف الدخل!',
    errorSetGoal: 'فشل في تحديث هدف الدخل.',
    successSourceAdded: 'تمت إضافة مصدر الدخل!',
    errorAddSource: 'فشل في إضافة مصدر الدخل.',
    successSourceUpdated: 'تم تحديث مصدر الدخل!',
    errorUpdateSource: 'فشل في تحديث مصدر الدخل.',
    successSourceDeleted: 'تم حذف مصدر الدخل.',
    errorDeleteSource: 'فشل في حذف مصدر الدخل.',
    successTransactionAdded: 'تمت إضافة معاملة الدخل.',
    errorAddTransaction: 'فشل في إضافة معاملة الدخل.',
    successTransactionDeleted: 'تم حذف المعاملة.',
    errorDeleteTransaction: 'فشل في حذف المعاملة.',
    successTransactionUpdated: 'تم تحديث حالة المعاملة.',
    errorUpdateTransaction: 'فشل في تحديث حالة المعاملة.',
    successColorsSaved: 'تم حفظ ألوان الفئات.',
    errorSaveColors: 'فشل في حفظ ألوان الفئات.',
    successMonthDeleted: 'تم حذف الميزانية الشهرية.',
    errorDeleteMonth: 'فشل في حذف الشهر.',
    successPaymentConfirmed: 'تم تأكيد الدفع بنجاح!',
    errorConfirmingPayment: 'خطأ في تأكيد الدفع.',
    recurringTransactionsUpdated: 'تم تحديث المعاملات المتكررة.',
    errorProcessingRecurring: 'فشل في معالجة المعاملات المتكررة.',
    successRecurringAdded: 'تمت إضافة المعاملة المتكررة.',
    errorRecurringAdd: 'فشل في إضافة المعاملة المتكررة.',
    successRecurringDeleted: 'تم حذف المعاملة المتكررة.',
    errorRecurringDelete: 'فشل في حذف المعاملة المتكررة.',
    
    // Categories
    category_food: 'طعام',
    category_transport: 'مواصلات',
    category_shopping: 'تسوق',
    category_bills: 'فواتير',
    category_entertainment: 'ترفيه',
    category_health: 'صحة',
    category_other: 'أخرى',

    // Income Categories
    incomeCategory_private_lesson: 'درس خصوصي',
    incomeCategory_italy_consultancy: 'استشارات إيطاليا',
    incomeCategory_refunds: 'مبالغ مستردة',
    incomeCategory_other: 'أخرى',
  },
};

const monthsByLang: Record<Language, string[]> = {
    en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    tr: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    it: ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
    ar: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"]
};

const monthsShortByLang: Record<Language, string[]> = {
    en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    tr: ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"],
    it: ["Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"],
    ar: ["ينا", "فبر", "مار", "أبر", "ماي", "يون", "يول", "أغس", "سبت", "أكت", "نوف", "ديس"]
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  availableLanguages: Language[];
  t: (key: string, options?: { [key: string]: string | number }) => string;
  months: string[];
  monthsShort: string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useLocalStorage<Language>('language', 'tr');
  const availableLanguages: Language[] = ['en', 'tr', 'it', 'ar'];

  const t = (key: string, options?: { [key: string]: string | number }) => {
    let text = (translations[language] as any)?.[key] || (translations.en as any)[key] || key;
    if (options) {
      Object.entries(options).forEach(([optionKey, value]) => {
        text = text.replace(`{{${optionKey}}}`, String(value));
      });
    }
    return text;
  };

  const value = {
    language,
    setLanguage,
    availableLanguages,
    t,
    months: monthsByLang[language],
    monthsShort: monthsShortByLang[language]
  };
  
  // For Arabic RTL text
  React.useEffect(() => {
    document.body.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);


  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};